@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzg4MzU0MDYsInVzZXJfaWQiOjF9.nAk3l8urmYB--fUd8e6O8RxJC19WIxJ3o6uKaDKHCA0

### 1. Регистрация
POST {{host}}/register
Content-Type: application/json

{
  "username": "dima",
  "email": "dima@mail.com",
  "password": "dima"
}

### 2. Логин (автоматически сохранит token)
POST {{host}}/login
Content-Type: application/json

{
  "email": "dima@mail.com",
  "password": "dima"
}

> {% client.global.set("token", response.body.token); %}

### 3. Создать счёт
POST {{host}}/accounts
Authorization: Bearer {{token}}


### 4. Пополнить счёт
POST {{host}}/accounts/topup
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "account_id": 1,
  "amount": 5000
}

### 5. Перевод со счёта 1 на счёт 2
POST {{host}}/transfer
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "from_account_id": 1,
  "to_account_id": 2,
  "amount": 1000
}

### 6. Выпустить карту
POST {{host}}/cards
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "account_id": 1
}

### 7. Получить мои счета
GET {{host}}/accounts
Authorization: Bearer {{token}}

### 8. Получить мои карты
GET {{host}}/cards
Authorization: Bearer {{token}}

### 9. Оформить кредит
POST {{host}}/credits
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "account_id": 1,
  "principal": 100000,
  "term_months": 12
}

### 10. График платежей
GET {{host}}/credits/1/schedule
Authorization: Bearer {{token}}